USE master
GO

-- Elimino base de datos Obligatorio si ya existe...
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'OBLIGATORIOFINAL')
BEGIN
	DROP DATABASE OBLIGATORIOFINAL
END 
GO

-- Creo la Base de Datos
CREATE DATABASE OBLIGATORIOFINAL
GO

USE OBLIGATORIOFINAL
GO

--Creo las tablas

CREATE TABLE Usuario
(
	IdLogueo INT NOT NULL PRIMARY KEY,
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR (20) NOT NULL,
	Contrasenia VARCHAR(20) NOT NULL,
	NroDoc INT NOT NULL,
	NombreLogueo VARCHAR (20) NOT NULL
)
GO

CREATE TABLE Cliente
(
	IdLogueo INT PRIMARY KEY FOREIGN KEY REFERENCES Usuario(IdLogueo) ON DELETE CASCADE,
	NroTarjeta BIGINT NOT NULL,
	Calle VARCHAR(20) NOT NULL,
	NroPuerta INT NOT NULL
)
GO

CREATE TABLE Administrador
(
	IdLogueo INT PRIMARY KEY FOREIGN KEY REFERENCES Usuario(IdLogueo) ON DELETE CASCADE,
	Cargo VARCHAR(20)
)
GO

CREATE TABLE Casa
(
	Rut BIGINT NOT NULL,
	IdEspe INT NOT NULL,
	Nombre VARCHAR (20) NOT NULL,
	PRIMARY KEY(Rut,IdEspe)
)
GO

CREATE TABLE Especializacion
(
	IdEspe INT FOREIGN KEY REFERENCES Casa(IdEspe) ON DELETE CASCADE,
	Tipo VARCHAR(20) NOT NULL,
)
GO

CREATE TABLE Plato
(
	IdPlato INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Precio INT NOT NULL
)

GO

CREATE TABLE Tienen
(
	Rut BIGINT FOREIGN KEY REFERENCES Casa(Rut) ON DELETE CASCADE,
	IdPlato INT FOREIGN KEY REFERENCES Plato(IdPlato) ON DELETE CASCADE,
	PRIMARY KEY(Rut,IdPlato)
)

GO

CREATE TABLE Pedido
(
	IdPedido INT PRIMARY KEY NOT NULL,
	Cantidad INT NOT NULL,
	Fecha DATETIME NOT NULL,
	Entregado BIT NOT NULL
)

GO

CREATE TABLE Compran
(
	IdPlato INT FOREIGN KEY REFERENCES Plato(IdPlato) ON DELETE CASCADE,
	IdLogueo INT FOREIGN KEY REFERENCES Usuario(IdLogueo) ON DELETE CASCADE
)

GO

CREATE TABLE Realizan
(
	IdPlato INT FOREIGN KEY REFERENCES Plato(IdPlato),
	IdLogueo INT FOREIGN KEY REFERENCES Usuario(IdLogueo),
	IdPedido INT NOT NULL PRIMARY KEY IDENTITY (1,1)
)

GO
